[package]
name = "jobstreet_jobs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
select = "0.6.0"
ureq = "2.9.1"
url = "2.5.0"
